language: ruby

before_script:
  - cp test/connections/databases.ci.yml test/connections/databases.yml
  - rake sqlite3:build_database postgresql:build_database

script:
  - "rake sqlite3:test"
  - "rake postgresql:test"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

env:
  CPK_LOGFILE: test.log
