dist: focal
language: ruby
sudo: false
bundler_args: --without "db2 oracle sqlserver"

before_script:
  - cp test/connections/databases.ci.yml test/connections/databases.yml
  - rake mysql:build_database postgresql:build_database sqlite:build_database

script:
  - "rake postgresql:test"
  - "rake sqlite:test"
  - "rake mysql:test"

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2

env:
  - CPK_LOGFILE=log/test.log

services:
  - postgresql

addons:
  - mariadb: "10.5"