language: ruby
sudo: false
bundler_args: --without "oracle sqlserver"

before_script:
  - cp test/connections/databases.ci.yml test/connections/databases.yml
  - rake mysql:build_database postgresql:build_database sqlite:build_database

script:
  - "rake postgresql:test"
  - "rake sqlite:test"
  - "rake mysql:test"

rvm:
  - 2.2.2
  - 2.3.0

env:
  - CPK_LOGFILE=log/test.log